language: cpp

sudo: false

matrix:
  include:
    - env: BUILD_TYPE="Debug"
      os: linux

    - env: BUILD_TYPE="Debug"
      os: osx

before_script:
  # print out some version numbers
  - g++ --version
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
script:
  - make -j2
  - make test