language: cpp

sudo: false

matrix:
  include:
    - env: CMAKE_CC="gcc-4.8" CMAKE_CXX="g++-4.8" BUILD_TYPE="Debug"
      os: linux
      addons: &gcc48
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports # cmake 3.2.3
          packages:
            - cmake
            - cmake-data
            - g++-4.8

    - env: CMAKE_CC="gcc-6" CMAKE_CXX="g++-6" BUILD_TYPE="Debug" COMPILER_FLAGS="-fopenmp"
      os: linux
      addons: &gcc6
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports # cmake 3.2.3
          packages:
            - cmake
            - cmake-data
            - g++-6

    - env: CMAKE_CC="gcc-6" CMAKE_CXX="g++-6" BUILD_TYPE="Release" COMPILER_FLAGS="-fopenmp"
      os: linux
      addons: *gcc6

before_script:
  # print out some version numbers
  - $CMAKE_CXX --version
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
script:
  - make -j2
  - make test